/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controllers.ItemController;
import Models.Item;
import Tools.JNumericField;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyListener;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Michail Sitmalidis
 */
public class MeasurementFrame extends javax.swing.JFrame {

    private JNumericField lengthField;
    private JNumericField widthField;
    private JNumericField mendingChargeField;
    private Font font;
    private SimpleDateFormat dateFormat;
    private Color focusInColor;
    private Color focusOutColor;
    private ItemController itemController;
    private Item item;

    public MeasurementFrame() {
        initComponents();
        myInitialization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        itemYear = new javax.swing.JComboBox<>();
        itemCodeField = new javax.swing.JFormattedTextField();
        itemCodeErrorLabel = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        widthPanel = new javax.swing.JPanel();
        widthErrorLabel = new javax.swing.JLabel();
        lengthErrorLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lengthPanel = new javax.swing.JPanel();
        itemSpotField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mendingChargePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        mendingChargeErrorLabel = new javax.swing.JLabel();
        mendingChargeButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        spotField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        saveSpotButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("ΧΡΟΝΙΑ/ΣΕΙΡΑ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ");

        itemYear.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        itemYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        try {
            itemCodeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        itemCodeField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        itemCodeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemCodeFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemCodeFieldFocusLost(evt);
            }
        });
        itemCodeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemCodeFieldKeyPressed(evt);
            }
        });

        itemCodeErrorLabel.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        itemCodeErrorLabel.setForeground(java.awt.Color.red);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        widthPanel.setBackground(new java.awt.Color(51, 255, 51));
        widthPanel.setLayout(new javax.swing.BoxLayout(widthPanel, javax.swing.BoxLayout.LINE_AXIS));

        widthErrorLabel.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        widthErrorLabel.setForeground(java.awt.Color.red);

        lengthErrorLabel.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        lengthErrorLabel.setForeground(java.awt.Color.red);

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        saveButton.setText("ΑΠΟΘΗΚΕΥΣΗ");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        saveButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveButtonKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("ΜΗΚΟΣ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("ΠΛΑΤΟΣ");

        lengthPanel.setBackground(new java.awt.Color(102, 255, 102));
        lengthPanel.setLayout(new javax.swing.BoxLayout(lengthPanel, javax.swing.BoxLayout.LINE_AXIS));

        itemSpotField.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        itemSpotField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemSpotFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemSpotFieldFocusLost(evt);
            }
        });
        itemSpotField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemSpotFieldKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setText("ΘΕΣΗ ΣΤΗΝ ΑΠΟΘΗΚΗ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 108, Short.MAX_VALUE)
                .addComponent(widthErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itemSpotField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lengthPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(widthPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lengthErrorLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lengthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lengthErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(widthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(widthErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemSpotField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("ΔΙΑΣΤΑΣΕΙΣ", jPanel1);

        mendingChargePanel.setBackground(new java.awt.Color(51, 255, 51));
        mendingChargePanel.setLayout(new javax.swing.BoxLayout(mendingChargePanel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel5.setText("ΧΡΕΩΣΗ ΕΠΙΔΙΟΡΘΩΣΗΣ");

        mendingChargeErrorLabel.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        mendingChargeErrorLabel.setForeground(java.awt.Color.red);

        mendingChargeButton.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        mendingChargeButton.setText("ΑΠΟΘΗΚΕΥΣΗ");
        mendingChargeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mendingChargeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mendingChargeErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(mendingChargePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mendingChargeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mendingChargePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mendingChargeErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(mendingChargeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ΕΠΙΔΙΟΡΘΩΣΗ", jPanel2);

        spotField.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        spotField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                spotFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                spotFieldFocusLost(evt);
            }
        });
        spotField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spotFieldKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel7.setText("ΘΕΣΗ ΣΤΗΝ ΑΠΟΘΗΚΗ");

        saveSpotButton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        saveSpotButton.setText("ΑΠΟΘΗΚΕΥΣΗ");
        saveSpotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveSpotButtonActionPerformed(evt);
            }
        });
        saveSpotButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                saveSpotButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveSpotButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spotField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spotField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveSpotButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ΘΕΣΗ", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itemYear, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(itemCodeErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jTabbedPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itemCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(itemYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(itemCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemCodeErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemCodeFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemCodeFieldKeyPressed
        if (evt.getKeyCode() == 10) {
            lengthField.requestFocus();
            mendingChargeField.requestFocus();
            spotField.requestFocus();
        }
    }//GEN-LAST:event_itemCodeFieldKeyPressed

    private void saveButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveButtonKeyPressed
        saveButton.doClick();
    }//GEN-LAST:event_saveButtonKeyPressed

    private void itemCodeFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemCodeFieldFocusLost
        itemCodeInputValid();        // TODO add your handling code here:
    }//GEN-LAST:event_itemCodeFieldFocusLost

    private void itemCodeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemCodeFieldFocusGained
        //  itemCodeField.setCaretPosition(itemCodeField.getDocument().getLength());
        itemCodeField.setBackground(focusInColor);
        itemCodeErrorLabel.setText("");
    }//GEN-LAST:event_itemCodeFieldFocusGained

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (itemDimensionsGoodToGo()) {
            // item.setCode(Integer.parseInt(itemCodeField.getText()));
            // item.setYear(Integer.parseInt(itemYear.getSelectedItem().toString()));
            item.setLength(new BigDecimal(lengthField.getText()));
            item.setWidth(new BigDecimal(widthField.getText()));
            item.setSpot(itemSpotField.getText());
            itemController.updateItemDimensions(item);
        }
        itemCodeField.setValue(null);
        lengthField.setText("");
        widthField.setText("");
        itemSpotField.setText("");
        itemCodeField.requestFocus();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void mendingChargeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mendingChargeButtonActionPerformed
        if (mendingChargeGoodToGo()) {
            item.setMendingCharge(new BigDecimal(mendingChargeField.getText()));
            itemController.updateItemMendingCharge(item);
        }
        itemCodeField.setValue(null);
        mendingChargeField.setText("");
        itemCodeField.requestFocus();
    }//GEN-LAST:event_mendingChargeButtonActionPerformed

    private void itemSpotFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemSpotFieldKeyPressed
        if (evt.getKeyCode() == 10) {
            saveButton.requestFocus();

        }
    }//GEN-LAST:event_itemSpotFieldKeyPressed

    private void itemSpotFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemSpotFieldFocusGained
        itemSpotField.setBackground(focusInColor);        // TODO add your handling code here:
    }//GEN-LAST:event_itemSpotFieldFocusGained

    private void itemSpotFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemSpotFieldFocusLost
        itemSpotField.setBackground(focusOutColor);
    }//GEN-LAST:event_itemSpotFieldFocusLost

    private void spotFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spotFieldFocusGained
        spotField.setBackground(focusInColor);
    }//GEN-LAST:event_spotFieldFocusGained

    private void spotFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spotFieldFocusLost
        spotField.setBackground(focusOutColor);
    }//GEN-LAST:event_spotFieldFocusLost

    private void spotFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spotFieldKeyPressed
        if (evt.getKeyCode() == 10) {
            saveSpotButton.requestFocus();

        }
    }//GEN-LAST:event_spotFieldKeyPressed

    private void saveSpotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSpotButtonActionPerformed

        if (itemCodeInputValid()) {//first i check code input
            item = itemController.getItemByCode(itemCodeField.getText().trim(), itemYear.getSelectedItem().toString());
            if (item != null) {
                item.setSpot(spotField.getText());
                itemController.updateItemSpot(item);

                itemCodeField.setValue(null);
                spotField.setText("");
                itemCodeField.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null,
                        "Ο ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ ΠΡΕΠΕΙ ΝΑ ΕΧΕΙ 5 ΨΗΦΙΑ",
                        "ΛΑΘΟΣ ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ",
                        JOptionPane.ERROR_MESSAGE
                );

            }

        } else {
            JOptionPane.showMessageDialog(null,
                    "Ο ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ ΔΕΝ ΥΠΑΡΧΕΙ ΣΤΗ ΒΑΣΗ",
                    "ΛΑΘΟΣ ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ",
                    JOptionPane.ERROR_MESSAGE
            );

            itemCodeField.setBackground(Color.red);
            itemCodeErrorLabel.setText("Ο ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ ΔΕΝ ΥΠΑΡΧΕΙ ΣΤΗ ΒΑΣΗ");
            itemCodeField.requestFocus();

        }


    }//GEN-LAST:event_saveSpotButtonActionPerformed

    private void saveSpotButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saveSpotButtonKeyPressed
        saveSpotButton.doClick();
    }//GEN-LAST:event_saveSpotButtonKeyPressed

    /**
     * @param args the command line arguments
     */
    private void myInitialization() {
        this.setTitle("ΚΑΤΑΧΩΡΗΣΗ ΔΙΑΣΤΑΣΕΩΝ");
        item = null;

        itemController = new ItemController();
        focusInColor = new Color(255, 255, 0);
        focusOutColor = new Color(240, 240, 240);
//setting year in itemYear Combobox
        dateFormat = new SimpleDateFormat("yyyy");
        String date = dateFormat.format(new Date());
        DefaultComboBoxModel model = (DefaultComboBoxModel) itemYear.getModel();
        int selectedIndex = model.getIndexOf(date);
        itemYear.setSelectedIndex(selectedIndex);

        font = new Font("Tahoma", Font.PLAIN, 36);
        lengthField = new JNumericField();
        // lengthField.setMaxLength(2); //2 is defaul, i dont think there is a carpet more then 99,99 meters long
        lengthField.setFont(font);
        lengthField.setAllowNegative(false);

        lengthField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == 10) {
                    widthField.requestFocus();
                }
            }
        });

        lengthField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lengthErrorLabel.setText("");
                lengthField.setBackground(focusInColor);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                lengthFieldGoodToGo();
            }
        });

        lengthPanel.add(lengthField);

        widthField = new JNumericField();
        widthField.setFont(font);
        widthField.setAllowNegative(false);
        widthField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                widthErrorLabel.setText("");
                widthField.setBackground(focusInColor);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                widthFieldGoodToGo();
            }
        });

        widthPanel.add(widthField);
        widthField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == 10) {
                    itemSpotField.requestFocus();

                }
            }
        });

        mendingChargeField = new JNumericField();
        mendingChargeField.setFont(font);
        mendingChargeField.setMaxLength(3);
        mendingChargeField.setAllowNegative(false);

        mendingChargeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mendingChargeErrorLabel.setText("");
                mendingChargeField.setBackground(focusInColor);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                mendingChargeFieldGoodToGo();
            }

        });

        mendingChargeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == 10) {
                    mendingChargeButton.requestFocus();
                }
            }
        });

        mendingChargePanel.add(mendingChargeField);

        itemCodeField.requestFocus();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemCodeErrorLabel;
    private javax.swing.JFormattedTextField itemCodeField;
    private javax.swing.JTextField itemSpotField;
    private javax.swing.JComboBox<String> itemYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lengthErrorLabel;
    private javax.swing.JPanel lengthPanel;
    private javax.swing.JButton mendingChargeButton;
    private javax.swing.JLabel mendingChargeErrorLabel;
    private javax.swing.JPanel mendingChargePanel;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveSpotButton;
    private javax.swing.JTextField spotField;
    private javax.swing.JLabel widthErrorLabel;
    private javax.swing.JPanel widthPanel;
    // End of variables declaration//GEN-END:variables

    private boolean itemCodeInputValid() {
        boolean valid = false;
        String id = itemCodeField.getText().trim();
        if (id.length() < 5) {

            itemCodeErrorLabel.setText("ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ ΠΡΕΠΕΙ ΝΑ ΕΧΕΙ 5 ΨΗΦΙΑ");
            itemCodeField.setBackground(Color.red);

        } else {
            itemCodeField.setBackground(focusOutColor);

            valid = true;
        }
        return valid;
    }

    private boolean dimensionInputEmpty(String input) {
        return (input.trim().length() == 0);
    }

    private boolean dimensionInputZero(String input) {
        return (Double.valueOf(input.trim()) == 0.0);
    }

    private boolean lengthFieldGoodToGo() {
        boolean goodToGo = false;
        String input = lengthField.getText().trim();
        switch (1) {
            case 1:
                if (dimensionInputEmpty(input)) {
                    lengthField.setBackground(Color.red);
                    lengthErrorLabel.setText("ΠΕΔΙΟ 'ΜΗΚΟΣ' ΔΕΝ ΜΠΟΡΕΙ ΝΑΙ ΕΙΝΑΙ ΑΔΕΙΟ");
                    break;
                }
            case 2:
                if (dimensionInputZero(input)) {
                    lengthField.setBackground(Color.red);
                    lengthErrorLabel.setText("ΠΕΔΙΟ 'ΜΗΚΟΣ' ΔΕΝ ΜΠΟΡΕΙ ΝΑ ΕΙΝΑΙ ΜΗΔΕΝ");
                    break;
                }
            case 3:
                lengthField.setBackground(focusOutColor);
                goodToGo = true;
        }
        return goodToGo;
    }

    private boolean widthFieldGoodToGo() {
        boolean goodToGo = false;
        String input = widthField.getText().trim();

        switch (1) {
            case 1:
                if (dimensionInputEmpty(input)) {
                    widthField.setBackground(Color.red);
                    widthErrorLabel.setText("ΠΕΔΙΟ 'ΠΛΑΤΟΣ' ΔΕΝ ΜΠΟΡΕΙ ΝΑΙ ΕΙΝΑΙ ΑΔΕΙΟ");
                    break;
                }
            case 2:
                if (dimensionInputZero(input)) {
                    widthField.setBackground(Color.red);
                    widthErrorLabel.setText("ΠΕΔΙΟ 'ΠΛΑΤΟΣ' ΔΕΝ ΜΠΟΡΕΙ ΝΑ ΕΙΝΑΙ ΜΗΔΕΝ");
                    break;
                }
            case 3:
                widthField.setBackground(focusOutColor);
                goodToGo = true;
        }
        return goodToGo;
    }

    private boolean itemDimensionsGoodToGo() {

        boolean goodToGo = false;
        switch (1) {
            case 1:
                if (itemCodeInputValid()) {//first i check code input
                    goodToGo = true;
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Ο ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ ΠΡΕΠΕΙ ΝΑ ΕΧΕΙ 5 ΨΗΦΙΑ",
                            "ΛΑΘΟΣ ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ",
                            JOptionPane.ERROR_MESSAGE
                    );
                    itemCodeField.setBackground(Color.red);
                    itemCodeErrorLabel.setText("Ο ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ ΠΡΕΠΕΙ ΝΑ ΕΧΕΙ 5 ΨΗΦΙΑ");

                    break;
                }
            case 2:
                //now i get item from db
                item = itemController.getItemByCode(itemCodeField.getText().trim(), itemYear.getSelectedItem().toString());
                if (item != null) {
                    goodToGo = true;
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Ο ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ ΔΕΝ ΥΠΑΡΧΕΙ ΣΤΗ ΒΑΣΗ",
                            "ΛΑΘΟΣ ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ",
                            JOptionPane.ERROR_MESSAGE
                    );
                    goodToGo = false;
                    itemCodeField.setBackground(Color.red);
                    itemCodeErrorLabel.setText("Ο ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ ΔΕΝ ΥΠΑΡΧΕΙ ΣΤΗ ΒΑΣΗ");
                    itemCodeField.requestFocus();
                    break;
                }
            case 3:
                if (lengthFieldGoodToGo()) {

                } else {
                    JOptionPane.showMessageDialog(null,
                            "ΛΑΘΟΣ ΣΤΟ ΠΕΔΙΟ ΜΗΚΟΣ",
                            "ΛΑΘΟΣ ΣΤΟ ΠΕΔΙΟ ΜΗΚΟΣ",
                            JOptionPane.ERROR_MESSAGE
                    );
                    goodToGo = false;

                    break;
                }
            case 4:
                if (widthFieldGoodToGo()) {
                    goodToGo = true;
                } else {
                    JOptionPane.showMessageDialog(null,
                            "ΛΑΘΟΣ ΣΤΟ ΠΕΔΙΟ platos",
                            "ΛΑΘΟΣ ΣΤΟ ΠΕΔΙΟ platos",
                            JOptionPane.ERROR_MESSAGE
                    );
                    goodToGo = false;

                    break;
                }
            case 5:
                if (item.getLength() != null || item.getWidth() != null) {
                    int result = JOptionPane.showConfirmDialog(null, "ΔΙΑΣΤΑΣΕΙΣ ΗΔΗ ΕΧΕΟΥΝ ΚΑΤΑΧΩΡΗΘΕΙ ΓΙΑ ΑΥΤΟΝ ΤΟΝ ΚΩΔΙΚΟ, ΘΕΣ ΝΑ ΤΟ ΑΛΛΑΞΕΙΣ?", "ΜΗΚΟΣ ΚΑΤΑΧΩΡΗΜΕΝΟ",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE);
                    if (result == JOptionPane.YES_OPTION) {
                        goodToGo = true;
                    } else if (result == JOptionPane.NO_OPTION) {
                        goodToGo = false;
                        break;
                    }

                } else {
                    goodToGo = true;
                }

        }
        return goodToGo;
    }

    private boolean mendingChargeFieldGoodToGo() {

        String input = mendingChargeField.getText().trim();

        if (dimensionInputEmpty(input)) {
            mendingChargeField.setBackground(Color.red);
            mendingChargeErrorLabel.setText("ΠΕΔΙΟ 'ΧΡΕΩΣΗ ΕΠΙΔΙΟΡΘΩΣΗΣ' ΔΕΝ ΜΠΟΡΕΙ ΝΑ ΕΙΝΑΙ ΑΔΕΙΟ");
            return false;
        } else {
            widthField.setBackground(focusOutColor);
            return true;
        }
    }

    private boolean mendingChargeGoodToGo() {
        boolean goodToGo = false;
        switch (1) {
            case 1:
                if (itemCodeInputValid()) {//first i check code input
                    goodToGo = true;
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Ο ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ ΠΡΕΠΕΙ ΝΑ ΕΧΕΙ 5 ΨΗΦΙΑ",
                            "ΛΑΘΟΣ ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ",
                            JOptionPane.ERROR_MESSAGE
                    );
                    itemCodeField.setBackground(Color.red);
                    itemCodeErrorLabel.setText("Ο ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ ΠΡΕΠΕΙ ΝΑ ΕΧΕΙ 5 ΨΗΦΙΑ");

                    break;
                }
            case 2:
                //now i get item from db
                item = itemController.getItemByCode(itemCodeField.getText().trim(), itemYear.getSelectedItem().toString());
                if (item != null) {
                    goodToGo = true;
                } else {
                    JOptionPane.showMessageDialog(null,
                            "Ο ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ ΔΕΝ ΥΠΑΡΧΕΙ ΣΤΗ ΒΑΣΗ",
                            "ΛΑΘΟΣ ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ",
                            JOptionPane.ERROR_MESSAGE
                    );
                    goodToGo = false;
                    itemCodeField.setBackground(Color.red);
                    itemCodeErrorLabel.setText("Ο ΚΩΔΙΚΟΣ ΤΕΜΑΧΙΟΥ ΔΕΝ ΥΠΑΡΧΕΙ ΣΤΗ ΒΑΣΗ");
                    itemCodeField.requestFocus();
                    break;
                }
            case 3:
                if (mendingChargeFieldGoodToGo()) {

                } else {
                    JOptionPane.showMessageDialog(null,
                            "ΛΑΘΟΣ ΣΤΟ ΠΕΔΙΟ ΧΡΕΩΣΗ ΕΠΙΔΙΟΡΘΩΣΗΣ",
                            "ΛΑΘΟΣ ΣΤΟ ΠΕΔΙΟ ΧΡΕΩΣΗ ΕΠΙΔΙΟΡΘΩΣΗΣ",
                            JOptionPane.ERROR_MESSAGE
                    );
                    goodToGo = false;

                    break;
                }

            case 4:
                if (item.getMendingCharge() != null) {
                    int result = JOptionPane.showConfirmDialog(null, "Η ΕΠΙΔΙΟΡΘΩΣΗ  ΗΔΗ ΕΧΕΙ ΧΡΕΩΘΕΙ, ΘΕΣ ΝΑ ΤΟ ΑΛΛΑΞΕΙΣ?", "ΕΠΙΔΙΟΡΘΩΣΗ ΧΡΕΟΜΕΝΟ",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE);
                    if (result == JOptionPane.YES_OPTION) {
                        goodToGo = true;
                    } else if (result == JOptionPane.NO_OPTION) {
                        goodToGo = false;
                        break;
                    }

                } else {
                    goodToGo = true;
                }
            case 5:
                if (!item.isForMending()) {
                    JOptionPane.showConfirmDialog(null, "ΤΟ ΤΕΜΑΧΙΟ ΔΕΝ ΕΙΝΑΙ ΓΙΑ ΕΠΙΔΙΟΡΘΩΣΗ!!!", "ΛΟΘΟΣ ΤΕΜΑΧΙΟ!!!",
                            JOptionPane.ERROR_MESSAGE);
                    goodToGo = false;
                    break;
                } else {
                    goodToGo = true;
                }
        }
        return goodToGo;
    }
}
