/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controllers.RoutController;
import Models.Rout;
import Tools.ImagePanel;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.Polygon;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.Popup;
import javax.swing.PopupFactory;

/**
 *
 * @author Michail Sitmalidis
 */
public class RoutPlanningFrame extends javax.swing.JFrame {
    
    private int lot;
    private HashMap<Integer, ArrayList<String>> lots;
    
    private ImagePanel imagePanel;
    
    private Popup popup;
    private Font popupFont;
    
    DefaultListModel districtsListModel;
    RoutController routController;
    
    public RoutPlanningFrame() {
        initComponents();
        myInitialization();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapPanel = new javax.swing.JPanel();
        Panel = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        disrtictListField = new javax.swing.JList<>();
        routNameField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        day_1Field = new javax.swing.JCheckBox();
        day_2Field = new javax.swing.JCheckBox();
        day_3Field = new javax.swing.JCheckBox();
        day_4Field = new javax.swing.JCheckBox();
        day_5Field = new javax.swing.JCheckBox();
        day_6Field = new javax.swing.JCheckBox();
        day_7Field = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        mapPanel.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 829, Short.MAX_VALUE)
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
        );

        getContentPane().add(mapPanel);

        Panel.setBackground(new java.awt.Color(153, 153, 255));

        jCheckBox1.setText("Popup Text Displayed");

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        disrtictListField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(disrtictListField);

        routNameField.setText("jTextField1");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("ΑΠΟΘΗΚΕΥΣΗ ΔΡΟΜΟΛΟΓΙΟΥ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );

        day_1Field.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        day_1Field.setText("ΔΕΥΤΕΡΑ");

        day_2Field.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        day_2Field.setText("ΤΡΙΤΗ");

        day_3Field.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        day_3Field.setText("ΤΕΤΑΡΤΗ");

        day_4Field.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        day_4Field.setText("ΠΕΠΜΠΤΗ");

        day_5Field.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        day_5Field.setText("ΠΑΡΑΣΚΕΥΗ");

        day_6Field.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        day_6Field.setText("ΣΑΒΒΑΤΟ");

        day_7Field.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        day_7Field.setText("ΚΥΡΙΑΚΗ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(day_1Field)
                    .addComponent(day_2Field)
                    .addComponent(day_4Field)
                    .addComponent(day_5Field)
                    .addComponent(day_6Field)
                    .addComponent(day_7Field)
                    .addComponent(day_3Field))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(routNameField)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(routNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(day_1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day_2Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day_3Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day_4Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day_5Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day_6Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(day_7Field)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("ΝΕΟ ΔΡΟΜΟΛΟΓΙΟ", jPanel1);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTabbedPane1)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(3, 3, 3)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        getContentPane().add(Panel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        imagePanel.clearChosenLots();
        showChosenDistricts(new HashSet());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Rout rout = collectRoutInformation();
        routController.saveRout(rout);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JCheckBox day_1Field;
    private javax.swing.JCheckBox day_2Field;
    private javax.swing.JCheckBox day_3Field;
    private javax.swing.JCheckBox day_4Field;
    private javax.swing.JCheckBox day_5Field;
    private javax.swing.JCheckBox day_6Field;
    private javax.swing.JCheckBox day_7Field;
    private javax.swing.JList<String> disrtictListField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JTextField routNameField;
    // End of variables declaration//GEN-END:variables

    private void myInitialization() {
        Image img = Toolkit.getDefaultToolkit().getImage(
                getClass().getResource("/image/ath_map.jpg"));
        MediaTracker tracker = new MediaTracker(this);
        tracker.addImage(img, 1);
        try {
            tracker.waitForAll();
        } catch (InterruptedException ie) {
        }
        imagePanel = new ImagePanel(img, this);
        imagePanel.setPreferredSize(new Dimension(img.getWidth(null), img.getHeight(null)));
        
        mapPanel.add(imagePanel);
        mapPanel.setLayout(new java.awt.BorderLayout());
        mapPanel.add(imagePanel, java.awt.BorderLayout.WEST);
        
        popupFont = new Font("Tahoma", Font.BOLD, 20);
        
        districtsListModel = new DefaultListModel();
        
        disrtictListField.setModel(districtsListModel);
        
        routController = new RoutController();
        
        Vector<Polygon> polys = new Vector<>();
        lots = new HashMap<>();
        
        int[] x;
        int[] y;

        //--ΒΑΡΗ-ΒΟΥΛΑ-ΒΟΥΛΙΑΓΜΕΝΗ
        x = new int[]{534, 536, 536, 515, 491, 491, 489, 473, 469, 471, 474, 477, 484, 542, 549, 558, 563, 574, 579, 596, 608, 624, 626, 624, 634, 645, 650, 648, 639, 650, 660, 671, 694, 701, 719, 721, 709, 701, 683};
        y = new int[]{945, 921, 919, 908, 881, 875, 872, 871, 869, 865, 862, 859, 857, 857, 846, 839, 834, 832, 829, 794, 794, 815, 822, 830, 843, 846, 855, 862, 875, 885, 885, 880, 879, 882, 882, 892, 906, 914, 945};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_0 = new ArrayList<>();
        lot_0.add("ΒΑΡΗ");
        lot_0.add("ΒΟΥΛΑ");
        lot_0.add("ΒΟΥΛΙΑΓΜΕΝΗ");
        lots.put(0, lot_0);

        //--ΓΛΥΦΑΔΑ
        x = new int[]{484, 482, 487, 468, 463, 443, 441, 437, 473, 498, 510, 511, 509, 513, 520, 531, 540, 543, 547, 554, 568, 588, 613, 615, 619, 626, 633, 632, 626, 585, 583, 596, 579, 574, 563, 558, 549, 542};
        y = new int[]{857, 854, 843, 824, 824, 806, 798, 791, 753, 745, 744, 727, 722, 715, 710, 697, 689, 687, 682, 680, 675, 673, 674, 690, 705, 714, 724, 732, 740, 767, 774, 794, 829, 832, 834, 839, 846, 857};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_1 = new ArrayList<>();
        lot_1.add("ΓΛΥΦΑΔΑ");
        
        lots.put(1, lot_1);

        //--ΕΛΛΗΝΙΚΟ, ΑΡΓΥΡΟΥΠΟΛΗ
        x = new int[]{437, 418, 416, 410, 407, 402, 403, 403, 407, 412, 417, 422, 452, 452, 448, 448, 452, 459, 462, 470, 483, 495, 501, 521, 527, 543, 555, 565, 572, 587, 621, 613, 588, 568, 554, 547, 543, 540, 531, 520, 513, 509, 511, 510, 498, 473, 437};
        y = new int[]{791, 751, 746, 739, 738, 729, 728, 718, 708, 700, 698, 701, 696, 686, 678, 674, 671, 670, 670, 651, 653, 653, 658, 659, 659, 656, 652, 649, 649, 651, 659, 674, 673, 675, 680, 682, 687, 689, 697, 710, 715, 722, 727, 744, 745, 753, 791};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_2 = new ArrayList<>();
        lot_2.add("ΑΡΓΥΡΟΥΠΟΛΗ");
        lot_2.add("ΕΛΛΗΝΙΚΟ");
        
        lots.put(2, lot_2);

        //--ΗΛΙΟΥΠΟΛΗ
        x = new int[]{470, 470, 462, 463, 471, 483, 497, 517, 524, 526, 539, 547, 564, 574, 612, 618, 618, 624, 627, 621, 587, 572, 565, 555, 543, 527, 521, 501, 495, 483, 470};
        y = new int[]{651, 604, 586, 582, 576, 560, 555, 554, 563, 568, 590, 592, 596, 598, 598, 613, 631, 641, 653, 659, 651, 649, 649, 652, 656, 659, 659, 658, 653, 653, 651};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_3 = new ArrayList<>();
        lot_3.add("ΗΛΙΟΥΠΟΛΗ");
        
        lots.put(3, lot_3);

        //--ΑΓΙΟΣ ΔΗΜΗΤΡΙΟΣ, ΑΛΙΜΟΣ, ΔΑΦΝΗ, ΥΜΗΤΤΟΣ,  ΝΕΑ ΣΜΥΡΝΗ, ΠΑΛΑΙΟ ΦΑΛΗΡΟ
        x = new int[]{412, 407, 398, 395, 383, 380, 373, 338, 337, 324, 321, 322, 322, 326, 329, 334, 339, 354, 396, 414, 423, 427, 435, 440, 447, 454, 463, 472, 477, 487, 490, 497, 483, 471, 463, 462, 470, 470, 462, 459, 452, 448, 448, 452, 452, 422, 417, 412};
        y = new int[]{700, 700, 691, 685, 679, 673, 666, 634, 629, 622, 622, 617, 610, 606, 605, 594, 592, 575, 538, 555, 546, 544, 538, 536, 536, 534, 535, 533, 530, 538, 545, 555, 560, 576, 582, 586, 604, 651, 670, 670, 671, 674, 678, 686, 696, 701, 698, 700};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_4 = new ArrayList<>();
        lot_4.add("ΑΓΙΟΣ ΔΗΜΗΤΡΙΟΣ");
        lot_4.add("ΑΛΙΜΟΣ");
        lot_4.add("ΔΑΦΝΗ");
        lot_4.add("ΥΜΗΤΤΟΣ");
        lot_4.add("ΝΕΑ ΣΜΥΡΝΗ");
        lot_4.add("ΠΑΛΑΙΟ ΦΑΛΗΡΟ");
        lots.put(4, lot_4);

        //--ΜΟΣΧΑΤΟ, ΚΑΛΛΙΘΕΑ, ΤΑΥΡΟΣ
        x = new int[]{334, 339, 354, 396, 408, 397, 378, 358, 370, 370, 346, 328, 316, 323, 320, 328, 319, 306, 298, 289, 288, 287, 287, 292, 303, 312, 313, 314, 318, 323};
        y = new int[]{594, 592, 575, 538, 524, 511, 511, 495, 484, 475, 472, 461, 474, 482, 490, 499, 513, 527, 528, 541, 557, 572, 572, 578, 582, 576, 578, 583, 588, 586};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_5 = new ArrayList<>();
        
        lot_5.add("ΜΟΣΧΑΤΟ");
        lot_5.add("ΚΑΛΛΙΘΕΑ");
        lot_5.add("ΤΑΥΡΟΣ");
        
        lots.put(5, lot_5);

        //--ΠΕΙΡΑΙΑΣ
        x = new int[]{183, 177, 177, 177, 175, 184, 193, 200, 210, 212, 212, 215, 215, 209, 205, 199, 193, 187, 179, 169, 169, 175, 176, 183, 190, 197, 205, 210, 219, 222, 223, 218, 220, 223, 227, 239, 246, 252, 257, 269, 275, 281, 287, 288, 289, 279, 276, 266, 258, 252, 249, 251, 250, 244, 238, 230, 223, 212, 205, 189, 183};
        y = new int[]{504, 514, 527, 532, 543, 548, 549, 554, 554, 557, 563, 569, 576, 584, 587, 587, 591, 591, 590, 596, 600, 604, 613, 618, 625, 622, 623, 622, 613, 606, 603, 596, 589, 586, 586, 598, 598, 590, 588, 580, 580, 576, 572, 557, 541, 541, 532, 527, 523, 523, 517, 508, 505, 503, 504, 513, 513, 512, 511, 510, 504};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_6 = new ArrayList<>();
        lot_6.add("ΠΕΙΡΑΙΑΣ");
        
        lots.put(6, lot_6);

        //--ΑΙΓΑΛΕΩ, ΑΓΙΟΣ ΙΩΑΝΝΗΣ ΡΕΝΤΗΣ, NIKAIA, ΚΟΡΥΔΑΛΛΟΣ, ΑΓΙΑ ΒΑΡΒΑΡΑ
        x = new int[]{328, 316, 323, 320, 328, 319, 306, 298, 289, 279, 276, 266, 258, 252, 249, 251, 250, 244, 238, 230, 223, 212, 205, 189, 183, 183, 185, 184, 173, 168, 163, 155, 149, 145, 135, 141, 155, 165, 177, 181, 175, 177, 183, 189, 197, 207, 218, 225, 230, 241, 247, 254, 257, 266, 270, 277, 277, 276, 280, 284, 304, 323, 342, 340, 350, 340, 328};
        y = new int[]{461, 474, 482, 490, 499, 513, 527, 528, 541, 541, 532, 527, 523, 523, 517, 508, 505, 503, 504, 513, 513, 512, 511, 510, 504, 489, 484, 465, 458, 452, 447, 441, 437, 429, 416, 410, 412, 410, 412, 408, 393, 384, 382, 384, 384, 385, 385, 394, 399, 398, 403, 406, 401, 402, 399, 395, 386, 384, 371, 368, 384, 392, 405, 409, 418, 439, 461};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_7 = new ArrayList<>();
        lot_7.add("ΑΙΓΑΛΕΩ");
        lot_7.add("ΑΓΙΑ ΒΑΡΒΑΡΑ");
        lot_7.add("ΑΓΙΟΣ ΙΩΑΝΝΗΣ ΡΕΝΤΗΣ");
        lot_7.add("ΚΟΡΥΔΑΛΛΟΣ");
        lot_7.add("NIKAIA");
        lots.put(7, lot_7);

        //--ΚΕΡΑΤΣΙΝΙ, ΔΡΑΠΕΤΣΟΝΑ
        x = new int[]{121, 135, 145, 149, 155, 163, 168, 173, 184, 185, 183, 183, 177, 177, 177, 175, 184, 193, 192, 192, 188, 162, 157, 151, 144, 147, 146, 146, 143, 132, 127, 124, 124, 125, 126, 129, 133, 138, 139, 137, 137, 129, 125, 124, 123, 115, 110, 113, 118, 119, 124, 131, 133, 132, 121};
        y = new int[]{425, 416, 429, 437, 441, 447, 452, 458, 465, 484, 489, 504, 514, 527, 532, 543, 548, 549, 555, 561, 566, 580, 581, 579, 574, 566, 559, 557, 555, 559, 559, 556, 551, 546, 542, 536, 533, 533, 529, 528, 524, 523, 517, 507, 502, 489, 480, 475, 471, 467, 462, 455, 450, 442, 425};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_8 = new ArrayList<>();
        lot_8.add("ΔΡΑΠΕΤΣΟΝΑ");
        lot_8.add("ΚΕΡΑΤΣΙΝΙ");
        
        lots.put(8, lot_8);

        //--ΠΕΡΑΜΑ
        x = new int[]{0, 4, 10, 16, 21, 26, 31, 34, 42, 54, 61, 67, 72, 79, 85, 90, 97, 106, 111, 121, 132, 133, 131, 124, 119, 118, 113, 110, 115, 123, 124, 119, 114, 109, 99, 87, 86, 87, 86, 80, 77, 74, 68, 63, 55, 42, 36, 17, 14, 12, 10, 4, 0};
        y = new int[]{447, 443, 440, 439, 436, 432, 424, 418, 418, 419, 423, 423, 425, 425, 429, 431, 427, 428, 421, 425, 442, 450, 455, 462, 467, 471, 475, 480, 489, 502, 507, 514, 515, 515, 523, 524, 528, 536, 542, 542, 532, 527, 524, 524, 516, 516, 512, 512, 513, 512, 513, 513, 513};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_9 = new ArrayList<>();
        lot_9.add("ΠΕΡΑΜΑ");
        
        lots.put(9, lot_9);

        //--ΧΑΙΔΑΡΙ
        x = new int[]{34, 42, 54, 61, 67, 72, 79, 85, 90, 97, 106, 111, 121, 135, 141, 155, 165, 177, 181, 175, 177, 183, 189, 197, 207, 218, 225, 230, 241, 247, 254, 257, 266, 270, 277, 277, 276, 280, 284, 287, 292, 282, 279, 265, 274, 265, 254, 243, 224, 211, 202, 197, 183, 175, 162, 143, 135, 129, 120, 118, 105, 92, 89, 98, 97, 95, 88, 80, 67, 59, 54, 47, 37, 32, 27};
        y = new int[]{418, 418, 419, 423, 423, 425, 425, 429, 431, 427, 428, 421, 425, 416, 410, 412, 410, 412, 408, 393, 384, 382, 384, 384, 385, 385, 394, 399, 398, 403, 406, 401, 402, 399, 395, 386, 384, 371, 368, 360, 352, 341, 324, 314, 291, 291, 292, 286, 306, 308, 308, 317, 316, 323, 328, 336, 334, 337, 338, 341, 339, 348, 352, 362, 369, 373, 386, 396, 406, 408, 408, 403, 401, 401, 405};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_10 = new ArrayList<>();
        lot_10.add("ΧΑΙΔΑΡΙ");
        
        lots.put(10, lot_10);

        //--ΠΕΡΙΣΤΕΡΙ
        x = new int[]{350, 340, 342, 323, 304, 284, 287, 292, 282, 279, 265, 274, 288, 296, 301, 306, 310, 316, 337, 343, 348, 355, 361, 369, 376, 385, 404, 403, 388, 375, 362, 361, 350};
        y = new int[]{418, 409, 405, 392, 384, 368, 360, 352, 341, 324, 314, 291, 284, 289, 285, 288, 287, 294, 317, 320, 322, 323, 327, 331, 340, 343, 348, 360, 376, 387, 394, 408, 418};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_11 = new ArrayList<>();
        lot_11.add("ΠΕΡΙΣΤΕΡΙ");
        
        lots.put(11, lot_11);

        //--ΑΓΙΟΙ ΑΝΑΡΓΙΡΟΙ, ΠΕΤΡΟΥΠΟΛΗ, ΙΛΙΟΝ, ΚΑΜΑΤΕΡΟ
        x = new int[]{274, 265, 254, 243, 274, 288, 296, 301, 306, 310, 316, 337, 343, 348, 355, 361, 369, 376, 385, 404, 429, 431, 434, 443, 445, 442, 446, 432, 431, 425, 408, 396, 393, 362, 355, 351, 343, 338, 324, 313, 304, 296, 286, 275, 261, 244, 243};
        y = new int[]{291, 291, 292, 286, 291, 284, 289, 285, 288, 287, 294, 317, 320, 322, 323, 327, 331, 340, 343, 348, 301, 297, 284, 269, 254, 246, 237, 228, 220, 207, 197, 197, 190, 190, 194, 202, 202, 200, 200, 198, 208, 217, 216, 224, 231, 257, 286};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_12 = new ArrayList<>();
        lot_12.add("ΑΓΙΟΙ ΑΝΑΡΓΙΡΟΙ");
        lot_12.add("ΠΕΤΡΟΥΠΟΛΗ");
        lot_12.add("ΙΛΙΟΝ");
        lot_12.add("ΚΑΜΑΤΕΡΟ");
        lots.put(12, lot_12);

        //--ΑΝΩ ΛΙΟΣΙΑ, ΖΕΦΥΡΙ, 
        x = new int[]{408, 396, 393, 362, 355, 351, 343, 338, 324, 313, 304, 296, 286, 275, 261, 244, 216, 209, 207, 222, 224, 218, 216, 223, 233, 242, 278, 300, 320, 337, 337, 347, 350, 369, 373, 385, 398, 412, 417, 416, 410, 408, 401, 394, 394, 398, 405, 406, 398, 403, 403, 414, 415, 411,};
        y = new int[]{197, 197, 190, 190, 194, 202, 202, 200, 200, 198, 208, 217, 216, 224, 231, 257, 241, 229, 208, 163, 155, 133, 92, 78, 69, 67, 49, 48, 38, 34, 34, 31, 33, 34, 31, 16, 15, 11, 24, 31, 34, 49, 56, 85, 101, 107, 112, 118, 126, 134, 139, 145, 172, 182};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_13 = new ArrayList<>();
        
        lot_13.add("ΑΝΩ ΛΙΟΣΙΑ");
        lot_13.add("ΖΕΦΥΡΙ");

        lots.put(13, lot_13);

        //--ΑΧΑΡΝΕΣ, ΘΡΑΚΟΜΑΚΕΔΟΝΕΣ
        x = new int[]{412, 417, 416, 410, 408, 401, 394, 394, 398, 405, 406, 398, 403, 403, 414, 415, 411, 408, 425, 431, 432, 446, 454, 464, 476, 480, 485, 490, 508, 516, 524, 531, 536, 543, 564, 575, 565, 552, 535, 524, 517, 501, 494, 484, 449, 439, 433, 422};
        y = new int[]{11, 24, 31, 34, 49, 56, 85, 101, 107, 112, 118, 126, 134, 139, 145, 172, 182, 197, 207, 220, 228, 237, 232, 223, 208, 193, 186, 183, 159, 153, 146, 142, 123, 114, 102, 72, 57, 45, 44, 33, 26, 23, 23, 18, 18, 12, 3, 8};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_14 = new ArrayList<>();
        
        lot_14.add("ΑΧΑΡΝΕΣ");
        lot_14.add("ΘΡΑΚΟΜΑΚΕΔΟΝΕΣ");
        
        lots.put(14, lot_14);

        //--ΝΕΑ ΧΑΛΚΗΔΟΝΑ, ΝΕΑ ΦΙΛΑΔΕΛΦΙΑ, ΜΕΤΑΜΟΡΦΩΣΗ, ΗΡΑΚΛΕΙΟ, ΝΕΑ ΙΩΝΙΑ ΛΥΚΟΒΡΥΣΗ, ΠΕΥΚΗ
        x = new int[]{404, 429, 431, 434, 443, 445, 442, 446, 454, 464, 476, 480, 485, 490, 508, 516, 524, 531, 542, 552, 558, 579, 590, 594, 590, 597, 609, 617, 611, 600, 594, 583, 575, 564, 561, 554, 562, 563, 545, 536, 530, 518, 509, 500, 489, 475, 466, 453, 449, 435};
        y = new int[]{348, 301, 297, 284, 269, 254, 246, 237, 232, 223, 208, 193, 186, 183, 159, 153, 146, 142, 148, 147, 144, 151, 152, 158, 171, 177, 180, 187, 201, 215, 234, 234, 239, 244, 253, 262, 275, 299, 289, 296, 295, 306, 299, 298, 304, 298, 290, 300, 308, 315};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_15 = new ArrayList<>();
        
        lot_15.add("ΝΕΑ ΧΑΛΚΗΔΟΝΑ");
        lot_15.add("ΝΕΑ ΦΙΛΑΔΕΛΦΙΑ");
        lot_15.add("ΜΕΤΑΜΟΡΦΩΣΗ");
        lot_15.add("ΗΡΑΚΛΕΙΟ");
        lot_15.add("ΝΕΑ ΙΩΝΙΑ");
        lot_15.add("ΛΥΚΟΒΡΥΣΗ");
        lot_15.add("ΠΕΥΚΗ");
        lots.put(15, lot_15);

        //--ΜΑΡΟΥΣΙ ΜΕΛΙΣΣΙΑ
        x = new int[]{617, 611, 600, 594, 583, 575, 564, 561, 554, 562, 563, 579, 584, 600, 618, 623, 632, 646, 654, 664, 671, 676, 689, 687, 680, 689, 689, 686, 675, 654, 648, 633};
        y = new int[]{187, 201, 215, 234, 234, 239, 244, 253, 262, 275, 299, 313, 312, 292, 295, 294, 296, 296, 294, 288, 280, 265, 256, 233, 226, 216, 205, 200, 199, 187, 187, 190};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_16 = new ArrayList<>();
        
        lot_16.add("ΜΑΡΟΥΣΙ");
        lot_16.add("ΜΕΛΙΣΣΙΑ");
        lots.put(16, lot_16);
        //-----

        //--ΚΗΦΙΣΙΑ, ΝΕΑ ΕΡΥΘΡΑΙΑ, ΠΟΛΙΤΕΙΑ
        x = new int[]{575, 564, 543, 536, 531, 542, 552, 558, 579, 590, 594, 590, 597, 609, 617, 633, 648, 654, 675, 686, 695, 700, 710, 716, 746, 763, 791, 817, 776, 753, 751, 741, 729, 723, 701, 685, 673, 667, 657, 649, 640, 637, 623, 614, 591, 575};
        y = new int[]{72, 102, 114, 123, 142, 148, 147, 144, 151, 152, 158, 171, 177, 180, 187, 190, 187, 187, 199, 200, 192, 184, 184, 176, 175, 160, 148, 138, 107, 82, 75, 77, 86, 86, 57, 40, 27, 34, 35, 45, 48, 60, 59, 57, 70, 72};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_17 = new ArrayList<>();
        
        lot_17.add("ΚΗΦΙΣΙΑ");
        lot_17.add("ΝΕΑ ΕΡΥΘΡΑΙΑ");
        lot_17.add("ΠΟΛΙΤΕΙΑ");
        lots.put(17, lot_17);

        //-----ΑΓΙΟΣ ΣΤΕΦΑΝΟΣ ΑΝΟΙΞΙΗ ΔΙΟΝΥΣΟΣ ΔΡΟΣΙΑ ΕΚΑΛΗ ΡΟΔΟΠΟΛΗ ΣΤΑΜΑΤΑ
        x = new int[]{868, 857, 817, 776, 753, 751, 741, 729, 723, 701, 685, 673, 669, 671, 868};
        y = new int[]{171, 168, 138, 107, 82, 75, 77, 86, 86, 57, 40, 27, 11, 0, 0};
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_18 = new ArrayList<>();
        lot_18.add("ΑΓΙΟΣ ΣΤΕΦΑΝΟΣ");
        lot_18.add("ΑΝΟΙΞΙΗ");
        lot_18.add("ΔΙΟΝΥΣΟΣ");
        lot_18.add("ΔΡΟΣΙΑ");
        lot_18.add("ΕΚΑΛΗ");
        lot_18.add("ΚΡΥΟΝΕΡΙ");
        lot_18.add("ΡΟΔΟΠΟΛΗ");
        lot_18.add("ΣΤΑΜΑΤΑ");
        lots.put(18, lot_18);

        //--ΠΕΝΤΕΛΗ ΝΕΑ ΠΕΝΤΕΛΗ
        x = new int[]{868, 863, 854, 846, 826, 822, 813, 804, 797, 780, 761, 736, 700, 689, 687, 680, 689, 689, 686, 695, 700, 710, 716, 746, 763, 791, 817, 857, 868};
        y = new int[]{253, 253, 251, 254, 261, 270, 275, 275, 269, 262, 267, 229, 259, 256, 233, 226, 216, 205, 200, 192, 184, 184, 176, 175, 160, 148, 138, 168, 171};
        
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_19 = new ArrayList<>();
        
        lot_19.add("ΠΕΝΤΕΛΗ");
        lot_19.add("ΝΕΑ ΠΕΝΤΕΛΗ");
        lots.put(19, lot_19);

        //-----ΑΝΘΟΥΣΑ, ΓΕΡΑΚΑΣ, ΓΛΥΚΑ ΝΕΡΑ, ΠΑΛΛΗΝΗ ,ΣΤΑΥΡΟΣ
        x = new int[]{868, 859, 848, 851, 846, 826, 822, 813, 804, 797, 780, 761, 749, 738, 722, 730, 718, 721, 721, 715, 705, 697, 697, 707, 705, 710, 710, 715, 720, 724, 739, 772, 787, 786, 796, 806, 817, 835, 843, 856, 868};
        y = new int[]{345, 348, 283, 277, 254, 261, 270, 275, 275, 269, 262, 267, 279, 293, 321, 328, 366, 375, 380, 389, 391, 406, 414, 432, 441, 449, 464, 467, 466, 470, 470, 470, 454, 448, 418, 427, 432, 444, 436, 437, 429};
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_20 = new ArrayList<>();
        lot_20.add("ΑΝΘΟΥΣΑ");
        lot_20.add("ΓΕΡΑΚΑΣ");
        lot_20.add("ΣΤΑΥΡΟΣ");
        lot_20.add("ΓΛΥΚΑ ΝΕΡΑ");
        lot_20.add("ΠΑΛΛΗΝΗ");
        
        lots.put(20, lot_20);

        //-----ΧΑΛΑΝΔΡΙ, ΨΥΧΙΚΟ, ΝΕΟ ΨΥΧΙΚΟ, ΒΡΙΛΗΣΙΑ ,ΦΙΛΟΘΕΗ
        x = new int[]{536, 545, 563, 579, 584, 600, 618, 623, 632, 646, 654, 664, 671, 676, 689, 700, 736, 761, 749, 738, 722, 709, 692, 681, 660, 642, 629, 578, 568, 557, 549, 532, 519, 517, 522, 519, 519, 526, 531, 532, 536};
        y = new int[]{296, 289, 299, 313, 312, 292, 295, 294, 296, 296, 294, 288, 280, 265, 256, 259, 229, 267, 279, 293, 321, 334, 321, 326, 333, 357, 367, 392, 384, 399, 392, 399, 383, 375, 365, 355, 342, 333, 328, 323, 296};
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_21 = new ArrayList<>();
        lot_21.add("ΒΡΙΛΗΣΙΑ");
        lot_21.add("ΧΑΛΑΝΔΡΙ");
        lot_21.add("ΨΥΧΙΚΟ");
        lot_21.add("ΝΕΟ ΨΥΧΙΚΟ");
        lot_21.add("ΦΙΛΟΘΕΗ");
        
        lots.put(21, lot_21);

        //-----ΑΓΙΑ ΠΑΡΑΣΚΕΥΗ, ΧΟΛΑΡΓΟΣ,  ΠΑΠΑΓΟΣ
        x = new int[]{722, 730, 718, 721, 721, 715, 705, 697, 697, 707, 705, 710, 710, 699, 678, 665, 658, 650, 614, 597, 566, 568, 572, 576, 587, 574, 578, 629, 642, 660, 681, 692, 709, 722};
        y = new int[]{321, 328, 366, 375, 380, 389, 391, 406, 414, 432, 441, 449, 464, 477, 468, 476, 474, 478, 486, 483, 446, 440, 437, 429, 419, 399, 392, 367, 357, 333, 326, 321, 334, 321};
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_22 = new ArrayList<>();
        lot_22.add("ΑΓΙΑ ΠΑΡΑΣΚΕΥΗ");
        lot_22.add("ΧΟΛΑΡΓΟΣ");
        lot_22.add("ΠΑΠΑΓΟΣ");
        
        lots.put(22, lot_22);

        //-----ΒΥΡΩΝΑΣ, ΚΑΙΣΑΡΙΑΝΗ, ΖΩΓΡΑΦΟΣ
        x = new int[]{612, 617, 631, 651, 651, 659, 662, 663, 655, 655, 665, 658, 650, 614, 597, 566, 537, 506, 504, 513, 511, 502, 490, 497, 496, 487, 474, 477, 487, 490, 497, 517, 524, 526, 539, 547, 564, 574, 612};
        y = new int[]{598, 591, 578, 570, 555, 539, 521, 507, 497, 493, 476, 474, 478, 486, 483, 446, 443, 458, 461, 476, 481, 484, 481, 499, 505, 507, 518, 530, 538, 545, 555, 554, 563, 568, 590, 592, 596, 598, 598};
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_23 = new ArrayList<>();
        lot_23.add("ΒΥΡΩΝΑΣ");
        lot_23.add("ΚΑΙΣΑΡΙΑΝΗ");
        lot_23.add("ΖΩΓΡΑΦΟΣ");
        lots.put(23, lot_23);

        //-----ΑΘΗΝΑ,ΓΑΛΑΤΣΙ
        x = new int[]{566, 537, 506, 504, 513, 511, 502, 490, 497, 496, 487, 474, 477, 472, 463, 454, 447, 440, 435, 427, 423, 414, 396, 408, 397, 378, 358, 370, 370, 346, 328, 340, 350, 361, 362, 375, 388, 403, 404, 435, 449, 453, 466, 475, 489, 500, 509, 518, 530, 536, 532, 531, 526, 519, 519, 522, 517, 519, 532, 549, 557, 568, 578, 574, 587, 576, 572, 568, 566};
        y = new int[]{446, 443, 458, 461, 476, 481, 484, 481, 499, 505, 507, 518, 530, 533, 535, 534, 536, 536, 538, 544, 546, 555, 538, 524, 511, 511, 495, 484, 475, 472, 461, 439, 418, 408, 394, 387, 376, 360, 348, 315, 308, 300, 290, 298, 304, 298, 299, 306, 295, 296, 323, 328, 333, 342, 355, 365, 375, 383, 399, 392, 399, 384, 392, 399, 419, 429, 437, 440, 446};
        polys.add(new Polygon(x, y, x.length));
        
        ArrayList<String> lot_24 = new ArrayList<>();
        lot_24.add("ΑΘΗΝΑ");
        lot_24.add("ΓΑΛΑΤΣΙ");
        
        lots.put(24, lot_24);

//----------
//----------
        imagePanel.setPolygons(polys);
        imagePanel.setFill(Color.GREEN);
        
    }
    
    public void showChosenDistricts(HashSet<Integer> chosenLots) {
        districtsListModel.clear();
        ArrayList<String> dl;
        for (Integer key : lots.keySet()) {
            if (chosenLots.contains(key)) {
                dl = lots.get(key);
                for (String district : dl) {
                    districtsListModel.addElement(district);
                }
            }
        }
    }
    
    public void hidePopup() {
        if (popup != null) {
            popup.hide();
        }
    }
    
    public void showHoveredLot(int currentLot, MouseEvent e) {
        
        if (popup != null) {
            popup.hide();
        }
        if (currentLot > -1 && jCheckBox1.isSelected()) {
            
            ArrayList districtsList = lots.get(currentLot);
            DefaultListModel listModel = new DefaultListModel();
            JList districts = new JList(listModel);
            districts.setFont(popupFont);
            for (Object disrtict : districtsList) {
                listModel.addElement(disrtict.toString());
            }
            
            popup = PopupFactory.getSharedInstance().getPopup(e.getComponent(), districts, e.getXOnScreen() + 20, e.getYOnScreen() + 20);
            popup.show();
            
        } else {
            
        }
        
    }
    
    private Rout collectRoutInformation() {
        System.out.println("need checcking here- collectRoutInformation ");
        Rout rout = new Rout();
        rout.setName(routNameField.getText());
        rout.setLotSet(imagePanel.getChosenLots());
        rout.setDay_1(day_1Field.isSelected());
        rout.setDay_2(day_2Field.isSelected());
        rout.setDay_3(day_3Field.isSelected());
        rout.setDay_4(day_4Field.isSelected());
        rout.setDay_5(day_5Field.isSelected());
        rout.setDay_6(day_6Field.isSelected());
        rout.setDay_7(day_7Field.isSelected());
        
        return rout;
    }
}
