/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controllers.ReportController;
import Models.Report;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Michail Sitmalidis
 */
public class ScheduledPickUpFrame extends javax.swing.JFrame {

    MainFrame mainFrame;
    ReportController reportController;

    public ScheduledPickUpFrame(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        reportController = new ReportController();
        initComponents();
        myInitialization();
        initEscapeAction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><center>ΠΡΟΓΡΑΜΜΑΤΙΣΜΕΝΑ PICK-UPs</center></html>");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        display.setFont(new java.awt.Font("Tahoma", 0, 24));
        JTableHeader header = display.getTableHeader();
        header.setFont(new java.awt.Font("Tahoma", 0, 24));
        display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ΠΕΛΑΤΗ", "ΗΜΕΡΟΜΗΝΙΑ", "ΕΠΙΘΕΤΟ", "ΟΝΟΜΑ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        display.setRowHeight(40);
        display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayMouseClicked(evt);
            }
        });
        display.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                displayKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(display);
        if (display.getColumnModel().getColumnCount() > 0) {
            display.getColumnModel().getColumn(0).setPreferredWidth(10);
            display.getColumnModel().getColumn(1).setResizable(false);
            display.getColumnModel().getColumn(1).setPreferredWidth(100);
            display.getColumnModel().getColumn(2).setResizable(false);
            display.getColumnModel().getColumn(2).setPreferredWidth(300);
            display.getColumnModel().getColumn(3).setResizable(false);
            display.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 986, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 138, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void displayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayKeyPressed
        if (evt.getKeyCode() == 10) {
            displaySelectedCustomer();
        }
    }//GEN-LAST:event_displayKeyPressed

    private void displayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMouseClicked
        if (evt.getClickCount() == 2) {
            displaySelectedCustomer();
        }
    }//GEN-LAST:event_displayMouseClicked

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        this.dispose();
    }//GEN-LAST:event_formWindowLostFocus


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void myInitialization() {
        DefaultTableModel model = (DefaultTableModel) display.getModel();
        ArrayList<Report> reports = reportController.getPickUpReports();
        for (Report report : reports) {
            Object[] row = new Object[4];
            row[0] = report.getCustomer().getId();
            DateFormat dateFormat = new SimpleDateFormat("dd-mm-yyyy");
            String date = dateFormat.format(report.getDate());
            row[1] = date;
            row[2] = report.getCustomer().getLastName();
            row[3] = report.getCustomer().getFirstName();
            model.addRow(row);
        }
    }

    private void initEscapeAction() {
        KeyStroke escapeKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE,
                0, false);
        Action escapeAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
//close the frame
                dispose();
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escapeKeyStroke,
                "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);
    }

    private void displaySelectedCustomer() {
        int selectedRow = display.getSelectedRow();
        if (selectedRow >= 0) {
            int customer_id = (int) display.getValueAt(selectedRow, 0);
            mainFrame.dispalyCustomerById(customer_id);
            mainFrame.fillTables();
            mainFrame.showNewPickUpTab();
            this.dispose();
        }
    }
}
