/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Models.Customer;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Michail Sitmalidis
 */
public class SearchFrame extends javax.swing.JFrame {

    MainFrame mainFrame;
    ArrayList<Customer> customers;

    /**
     * Creates new form SearchFrame
     */
    public SearchFrame(MainFrame mainFrame, ArrayList<Customer> customers) {

        this.mainFrame = mainFrame;
        initComponents();
        initEscapeAction();
        displayCustomers(customers);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        display.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JTableHeader header = display.getTableHeader();
        header.setFont(new java.awt.Font("Tahoma", 0, 24));
        display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ΕΠΙΘΕΤΟ", "ΟΝΟΜΑ", "ΣΤΑΘΕΡΟ", "ΚΙΝΗΤΟ", "ΟΔΟΣ", "ΠΕΡΙΟΧΗ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        display.setRowHeight(32);
        display.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayMouseClicked(evt);
            }
        });
        display.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                displayKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(display);
        if (display.getColumnModel().getColumnCount() > 0) {
            display.getColumnModel().getColumn(0).setPreferredWidth(80);
            display.getColumnModel().getColumn(1).setPreferredWidth(350);
            display.getColumnModel().getColumn(2).setPreferredWidth(200);
            display.getColumnModel().getColumn(3).setPreferredWidth(150);
            display.getColumnModel().getColumn(4).setPreferredWidth(150);
            display.getColumnModel().getColumn(5).setPreferredWidth(200);
            display.getColumnModel().getColumn(6).setPreferredWidth(150);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void initEscapeAction() {
        KeyStroke escapeKeyStroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE,
                0, false);
        Action escapeAction = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
//close the frame
                dispose();
            }
        };
        getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(escapeKeyStroke,
                "ESCAPE");
        getRootPane().getActionMap().put("ESCAPE", escapeAction);

    }

    private void displayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayMouseClicked

        if (evt.getClickCount() == 2) {
            displaySelectedCustomer();
        }
    }//GEN-LAST:event_displayMouseClicked

    private void displayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_displayKeyPressed
        if (evt.getKeyCode() == 10) {
            displaySelectedCustomer();
        }
    }//GEN-LAST:event_displayKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable display;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void displayCustomers(ArrayList<Customer> customers) {
        DefaultTableModel model = (DefaultTableModel) display.getModel();
        for (Customer customer : customers) {
            Object[] row = new Object[7];
            row[0] = customer.getId();
            row[1] = customer.getLastName();
            row[2] = customer.getFirstName();
            row[3] = customer.getLandlinePhone();
            row[4] = customer.getMobilePhone();
            row[5] = customer.getStreet();
            row[6] = customer.getDistrict();
            model.addRow(row);

        }

    }

    private void displaySelectedCustomer() {
        int selectedRow = display.getSelectedRow();
        if (selectedRow >= 0) {
            int customer_id = (int) display.getValueAt(selectedRow, 0);
            mainFrame.dispalyCustomerById(customer_id);
            mainFrame.fillTables();
            this.dispose();
        }
    }
}
