/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tools;

import Controllers.ReportController;
import GUI.DayRoutsFrame;
import Models.Item;
import Models.Report;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Michail Sitmalidis
 */
public class NewJPanel extends javax.swing.JPanel {

    ReportController reportController;
    DayRoutsFrame frame;

    public NewJPanel() {
        initComponents();
        init();
    }

    public NewJPanel(DayRoutsFrame frame, Report report) {
        this.frame = frame;
        initComponents();
        init();
        fillReport(report);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        floor = new javax.swing.JTextField();
        name_on_bell = new javax.swing.JTextField();
        total_sum = new javax.swing.JTextField();
        report_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        postal_code = new javax.swing.JTextField();
        district_street_num = new javax.swing.JTextField();
        name_surname = new javax.swing.JTextField();
        landline_phone = new javax.swing.JTextField();
        mobile_phone = new javax.swing.JTextField();
        deliveryReceiptPanel = new javax.swing.JPanel();
        deliveryReceiptNumber = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        floor.setEditable(false);
        floor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        floor.setText("Floor");

        name_on_bell.setEditable(false);
        name_on_bell.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name_on_bell.setText("NameOnBell");

        total_sum.setEditable(false);
        total_sum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_sum.setText("TotalSum");

        report_id.setEditable(false);
        report_id.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        report_id.setText("reportId");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("CancelReport");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        postal_code.setEditable(false);
        postal_code.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        postal_code.setText("PostalCode");

        district_street_num.setEditable(false);
        district_street_num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        district_street_num.setText("District, Street, Numb");

        name_surname.setEditable(false);
        name_surname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name_surname.setText("Name");
        name_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_surnameActionPerformed(evt);
            }
        });

        landline_phone.setEditable(false);
        landline_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        landline_phone.setText("LandlinePhone");

        mobile_phone.setEditable(false);
        mobile_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mobile_phone.setText("MobilePhone");

        deliveryReceiptNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deliveryReceiptNumber.setText("DeliveryReceipNumber");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Delivered");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deliveryReceiptPanelLayout = new javax.swing.GroupLayout(deliveryReceiptPanel);
        deliveryReceiptPanel.setLayout(deliveryReceiptPanelLayout);
        deliveryReceiptPanelLayout.setHorizontalGroup(
            deliveryReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveryReceiptPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(deliveryReceiptPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(deliveryReceiptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        deliveryReceiptPanelLayout.setVerticalGroup(
            deliveryReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryReceiptPanelLayout.createSequentialGroup()
                .addComponent(deliveryReceiptNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name_on_bell, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(total_sum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(report_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(district_street_num, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(postal_code, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(name_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(landline_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mobile_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(deliveryReceiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliveryReceiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(landline_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobile_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(postal_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(district_street_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_on_bell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(total_sum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(report_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addGap(221, 221, 221))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1158, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(601, 601, 601))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void init() {
        reportController = new ReportController();

    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reportController.cancelReport(report_id.getText());
        frame.loadReports();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void name_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_surnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        reportController.deliverReport(report_id.getText(), deliveryReceiptNumber.getText());
        frame.loadReports();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deliveryReceiptNumber;
    private javax.swing.JPanel deliveryReceiptPanel;
    private javax.swing.JTextField district_street_num;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JTextField floor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField landline_phone;
    private javax.swing.JTextField mobile_phone;
    private javax.swing.JTextField name_on_bell;
    private javax.swing.JTextField name_surname;
    private javax.swing.JTextField postal_code;
    private javax.swing.JTextField report_id;
    private javax.swing.JTextField total_sum;
    // End of variables declaration//GEN-END:variables

    private void fillReport(Report report) {
        name_surname.setText(report.getCustomer().getLastName() + " " + report.getCustomer().getFirstName());
        district_street_num.setText(report.getCustomer().getDistrict() + ", " + report.getCustomer().getStreet());
        postal_code.setText(report.getCustomer().getPostalCode());
        floor.setText(report.getCustomer().getFloor());
        name_on_bell.setText(report.getCustomer().getDoorbellName());
        landline_phone.setText(report.getCustomer().getLandlinePhone());
        mobile_phone.setText(report.getCustomer().getMobilePhone());
        report_id.setText(String.valueOf(report.getId()));

        DefaultTableModel model = new DefaultTableModel();
        for (Item item : report.getItems()) {
            Object[] column = new Object[9];
            column[0] = "Description";
            column[1] = "ΘΕΣΗ";
            column[2] = "ΚΩΔΙΚΟΣ";
            column[3] = "ΧΡΩΝΙΑ";
            column[4] = "ΜΗΚΟΣ";
            column[5] = "ΠΛΑΤΟΣ";
            column[6] = "ΚΑΘΑΡΙΣΜΑ";
            column[7] = "ΦΥΛΑΞΗ";
            column[8] = "ΕΠΙΔΙΟΡΘΩΣΗ";

            model.setColumnIdentifiers(column);

            String[] row = new String[9];
            row[0] = item.getDescription();
            row[1] = "ΧΧΧΧ";
            row[2] = String.valueOf(item.getCode());
            row[3] = String.valueOf(item.getYear());
            row[4] = String.valueOf(item.getLength());
            row[5] = String.valueOf(item.getWidth());
            row[6] = String.valueOf(item.getCleaningCharge());
            row[7] = String.valueOf(item.getStoringCharge());
            row[8] = String.valueOf(item.getMendingCharge());
            model.addRow(row);
        }

        JTable table = new JTable();

        table.setModel(model);

        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(table.getTableHeader(), BorderLayout.NORTH);
        jPanel2.add(table, BorderLayout.CENTER);

    }

    public void hideDeliveryReceiptPanel() {
        deliveryReceiptPanel.hide();
    }
}
