/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tools;

import Controllers.ReportController;
import GUI.MainFrame;

/**
 *
 * @author Michail Sitmalidis
 */
public class ScheduledPickUpPanel extends javax.swing.JPanel {

    MainFrame mainFrame;
    int report_id;
    ReportController reportController;

    public ScheduledPickUpPanel(MainFrame mainFrame, int report_id, String route) {
        this.mainFrame = mainFrame;
        reportController = new ReportController();
        initComponents();
        this.report_id = report_id;
        scheduledPickUpLabel.setText(route);
    }

    public int getReport_id() {
        return report_id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scheduledPickUpLabel = new javax.swing.JLabel();
        deletScheduledPickUp = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));

        scheduledPickUpLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        deletScheduledPickUp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        deletScheduledPickUp.setText("<html><center>ΑΚΥΡΩΣΕ<br> ΕΠΙΣΚΕΨΗ</center></html>");
        deletScheduledPickUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletScheduledPickUpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(scheduledPickUpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deletScheduledPickUp, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(scheduledPickUpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(deletScheduledPickUp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deletScheduledPickUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletScheduledPickUpActionPerformed
        reportController.cancelPickUpReport(report_id);
        mainFrame.displayScheduledPickUps();
    }//GEN-LAST:event_deletScheduledPickUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletScheduledPickUp;
    private javax.swing.JLabel scheduledPickUpLabel;
    // End of variables declaration//GEN-END:variables
}
